"""Add AI processing fields to Email Model

Revision ID: 20dd999afa43
Revises: bda6d83419dc
Create Date: 2025-11-10 06:52:31.232409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20dd999afa43'
down_revision: Union[str, None] = 'bda6d83419dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email', sa.Column('sender', sa.String(), nullable=True))
    op.add_column('email', sa.Column('priority', sa.String(), nullable=True))
    op.add_column('email', sa.Column('entities', sa.JSON(), nullable=True))
    op.add_column('email', sa.Column('reply_suggestions', sa.JSON(), nullable=True))
    op.add_column('email', sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email', 'processed_at')
    op.drop_column('email', 'reply_suggestions')
    op.drop_column('email', 'entities')
    op.drop_column('email', 'priority')
    op.drop_column('email', 'sender')
    # ### end Alembic commands ###
